# Generated by Django 3.1.5 on 2021-01-17 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Номер')),
                ('count', models.IntegerField(verbose_name='Вместимость, чел.')),
                ('type', models.CharField(max_length=10, verbose_name='Тип номера')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена за сутки, руб.')),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=11, verbose_name='Номер телефона')),
                ('amount', models.IntegerField(verbose_name='Количество постояльцев')),
                ('data1', models.DateField(verbose_name='Дата заезда')),
                ('data2', models.DateField(verbose_name='Дата выезда')),
                ('number', models.ManyToManyField(related_name='Number_room', to='hotel.Room', verbose_name='Номер')),
            ],
        ),
    ]
